server {
  listen 80;

  # Serve static files
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  # Allow access to runtime environment variables
  location /env-config.js {
    root /usr/share/nginx/html;
  }

  # Error handling
  error_page 404 /index.html;
}