version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        - FLASK_ENV=production
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
      POSTGRES_DB: palace_of_goods_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
