version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - palace-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mongodb://db:27017/palace-of-goods
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - palace-network

  db:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - palace-network

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - palace-network

volumes:
  mongo-data:

networks:
  palace-network:
    driver: bridge
