name: Checkmarx Security Scan

# Trigger on pull requests and pushes to the main and staging branches
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main", "staging" ]  # Customize if you want to trigger on more branches
  push:
    branches: [ "main", "staging" ]  # Trigger on direct pushes to main or staging branches

permissions:
  contents: read
  security-events: write  # Required for SARIF results upload
  actions: read  # For accessing actions in private repos

jobs:
  security_scan:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Checkmarx One Security Scan (SAST, SCA, KICS)
      - name: Run Checkmarx One security scan (SAST, SCA, KICS)
        uses: checkmarx/ast-github-action@8e887bb93dacc44e0f5b64ee2b06d5815f89d4fc
        with:
          base_uri: https://ast.checkmarx.net  # Checkmarx One instance URI (default URL)
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}  # Stored in GitHub secrets
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}  # Stored in GitHub secrets
          cx_tenant: ${{ secrets.CX_TENANT }}  # Stored in GitHub secrets
          additional_params: |
            --scan-type sast      # Static Application Security Testing (SAST) for code vulnerabilities
            --scan-type sca       # Software Composition Analysis (SCA) for third-party library vulnerabilities
            --scan-type kics      # Kubernetes Infrastructure as Code (KICS) for security issues in K8s configurations
            --depth 5             # Increase scan depth for thorough analysis (adjust as needed)
            --report-format sarif # SARIF report format for GitHub integration
            --output-path ./checkmarx-results  # Output folder for scan results

      # Step 3: Upload SARIF results to GitHub
      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./checkmarx-results/cx_result.sarif  # Path to SARIF file generated by Checkmarx scan
