name: Code Scans
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    name: Security and Quality Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install bandit flake8
      - name: Static Code Analysis
        run: |
          flake8 app/
          bandit -r app/